export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGIN_FAILS = "USER_LOGIN_FAILS";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

export const USER_REGISTER_FAILS = "USER_REGISTER_FAILS";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";

export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";

export const USER_DETAILS_FAILS = "USER_DETAILS_FAILS";

export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";

export const USER_UPDATE_FAILS = "USER_UPDATE_FAILS";

export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_SAVEADDRESS_REQUEST = "USER_SAVEADDRESS_REQUEST";

export const USER_SAVEADDRESS_SUCCESS = "USER_SAVEADDRESS_SUCCESS";

export const USER_SAVEADDRESS_FAILS = "USER_SAVEADDRESS_FAILS";

export const USER_GETADDRESS_REQUEST = "USER_GETADDRESS_REQUEST";

export const USER_GETADDRESS_SUCCESS = "USER_GETADDRESS_SECCESS";

export const USER_GETADDRESS_FAILS = "USER_GETADDRESS_FAILS";